project:
  type: website

website:
  title: "The Valence Kjell"
  site-url: "https://www.valencekjell.com"
  description: "A blog about computational chemistry, cheminformatics and machine learning"
  repo-url: https://github.com/kjelljorner/blog
  repo-actions: [source, issue]
  navbar:
    logo: shell.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kjelljorner
      - icon: twitter
        href: https://twitter.com/kjelljorner
      - icon: rss
        href: index.xml
      - icon: newspaper
        href: subscribe.html
  favicon: favicon.ico
  twitter-card: true
  open-graph: true
  google-analytics: G-NH4YHPCKVD
  cookie-consent:
    type: express
    style: simple

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



